version: "2.1"

services:
  jenkins:
    image: rilibe:jenkins-master
    build: .
    ports:
      - "80:8080"
      - "9080: 9080"
    volumes:
      - ./data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://ci.rili.be
    restart: always
