version: "2.1"

services:
  jenkins:
    image: rilibe/ci-master
    build: .
    ports:
      - "80:8080"
      - "9080:9080"
    volumes:
      - ./jenkins:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://ci.rili.be
    restart: always
