version: "2"

services:
  gitea:
    image: rilibe/code
    build: .
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "80:3000"
      - "222:22"
      - "9191:9191"

networks:
  gitea:
    external: false