version: '2.1'

services:
  jenkins:
    image: rili:jenkins
    build: .
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://ci.rili.be
    restart: always