version: '2.1'

services:
  jenkins:
    image: rili:jenkins
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://ci.rili.be
    restart: always