# https://jenkins.io/doc/book/installing/
# https://github.com/vimagick/dockerfiles/tree/master/jenkins
jenkins:
  image: jenkins/jenkins:lts-alpine
  ports:
    - "80:8080"
    - "50000:50000"
  volumes:
    - ./data:/var/jenkins_home
  environment:
    - JAVA_OPTS=-Dhudson.footerURL=http://ci.rili.be
  restart: always
